import { prisma } from "../lib/db";

const baselineFoods = [
  {
    name: "Banana",
    category: "FRUITS",
    servingSize: 100,
    servingUnit: "g",
    calories: 89,
    protein: 1.1,
    carbohydrates: 22.8,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12.2,
    potassium: 358,
    vitaminC: 8.7,
    isSystemFood: true,
  },
  {
    name: "Apple (Raw, with skin)",
    category: "FRUITS",
    servingSize: 100,
    servingUnit: "g",
    calories: 52,
    protein: 0.3,
    carbohydrates: 13.8,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10.4,
    potassium: 107,
    vitaminC: 4.6,
    isSystemFood: true,
  },
  {
    name: "Whole Milk (Pasteurized)",
    category: "DAIRY",
    servingSize: 100,
    servingUnit: "ml",
    calories: 61,
    protein: 3.2,
    carbohydrates: 4.8,
    fat: 3.3,
    fiber: 0,
    sugar: 4.8,
    calcium: 120,
    sodium: 43,
    isSystemFood: true,
  },
  {
    name: "Greek Yogurt / Curd",
    category: "DAIRY",
    servingSize: 100,
    servingUnit: "g",
    calories: 73,
    protein: 10.0,
    carbohydrates: 3.8,
    fat: 2.0,
    fiber: 0,
    sugar: 3.5,
    calcium: 110,
    sodium: 36,
    isSystemFood: true,
  },
  {
    name: "Paneer (Indian Cottage Cheese)",
    category: "DAIRY",
    servingSize: 100,
    servingUnit: "g",
    calories: 265,
    protein: 18.3,
    carbohydrates: 1.2,
    fat: 20.8,
    fiber: 0,
    sugar: 1.0,
    calcium: 208,
    sodium: 19,
    isSystemFood: true,
  },
  {
    name: "Brown Rice (Cooked)",
    category: "GRAINS_CEREALS",
    servingSize: 100,
    servingUnit: "g",
    calories: 111,
    protein: 2.6,
    carbohydrates: 23.0,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.4,
    magnesium: 43,
    isSystemFood: true,
  },
  {
    name: "Yellow Dal / Moong Lentils (Cooked)",
    category: "PULSES_LEGUMES",
    servingSize: 100,
    servingUnit: "g",
    calories: 105,
    protein: 7.0,
    carbohydrates: 18.0,
    fat: 0.5,
    fiber: 6.0,
    sugar: 1.0,
    iron: 1.4,
    potassium: 290,
    isSystemFood: true,
  },
  {
    name: "Chickpeas / Chana (Boiled)",
    category: "PULSES_LEGUMES",
    servingSize: 100,
    servingUnit: "g",
    calories: 164,
    protein: 8.9,
    carbohydrates: 27.4,
    fat: 2.6,
    fiber: 7.6,
    sugar: 4.8,
    iron: 2.9,
    folate: 172,
    isSystemFood: true,
  },
  {
    name: "Rolled Oats (Dry)",
    category: "GRAINS_CEREALS",
    servingSize: 100,
    servingUnit: "g",
    calories: 389,
    protein: 16.9,
    carbohydrates: 66.3,
    fat: 6.9,
    fiber: 10.6,
    sugar: 0.9,
    magnesium: 177,
    iron: 4.7,
    isSystemFood: true,
  },
  {
    name: "Raw Almonds",
    category: "NUTS_SEEDS",
    servingSize: 100,
    servingUnit: "g",
    calories: 579,
    protein: 21.2,
    carbohydrates: 21.6,
    fat: 49.9,
    fiber: 12.5,
    sugar: 4.4,
    calcium: 269,
    magnesium: 270,
    isSystemFood: true,
  },
];

async function seed() {
  console.log("🌱 Seeding baseline nutritious foods...");
  for (const food of baselineFoods) {
    try {
      await prisma.food.create({
        data: food as any,
      });
      console.log(`  ✓ Added ${food.name}`);
    } catch (err: any) {
      console.log(`  - Skipping ${food.name}: already exists or error (${err.message})`);
    }
  }
  console.log("✅ Seed completed successfully.");
}

seed().catch(console.error);
