/**
 * Canonical 63-Nutrient Taxonomy & Registry
 * Correlated directly from the Nutri-Track Health OS / Nutrition Coach Workbook.
 */

export type NutrientCategory =
  | "ENERGY"
  | "MACRONUTRIENT"
  | "VITAMIN"
  | "MINERAL"
  | "AMINO_ACID"
  | "OTHER";

export type TargetType = "MINIMUM" | "MAXIMUM" | "RANGE" | "REFERENCE";

export type StandardUnit = "kcal" | "g" | "mg" | "µg" | "µg RAE" | "µg DFE" | "ml";

export interface NutrientDefinition {
  key: string;
  name: string;
  category: NutrientCategory;
  unit: StandardUnit;
  targetType: TargetType;
  defaultDailyTarget?: number;
  defaultUpperLimit?: number;
  description: string;
  isEssential: boolean;
}

export const COMPLETE_NUTRIENT_TAXONOMY: NutrientDefinition[] = [
  // =========================================================================
  // 1. ENERGY & MACRONUTRIENTS (15)
  // =========================================================================
  {
    key: "calories",
    name: "Calories",
    category: "ENERGY",
    unit: "kcal",
    targetType: "RANGE",
    defaultDailyTarget: 2000,
    description: "Total dietary energy consumed from protein, carbohydrates, fats, and organic acids.",
    isEssential: true,
  },
  {
    key: "protein",
    name: "Protein",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 140,
    description: "Primary building block for muscle repair, enzymatic reactions, and cellular synthesis.",
    isEssential: true,
  },
  {
    key: "carbohydrates",
    name: "Carbohydrates",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "RANGE",
    defaultDailyTarget: 225,
    description: "Primary rapid fuel source for brain activity and high-intensity glycolytic exercise.",
    isEssential: false,
  },
  {
    key: "net_carbohydrates",
    name: "Net Carbohydrates",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "RANGE",
    defaultDailyTarget: 190,
    description: "Total carbohydrates minus dietary fiber and non-metabolized sugar alcohols.",
    isEssential: false,
  },
  {
    key: "fat",
    name: "Fat",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "RANGE",
    defaultDailyTarget: 65,
    description: "Essential lipid substrate for steroid hormone synthesis and fat-soluble vitamin absorption.",
    isEssential: true,
  },
  {
    key: "saturated_fat",
    name: "Saturated Fat",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "MAXIMUM",
    defaultUpperLimit: 20,
    description: "Fatty acids without double bonds; recommended to keep below 10% of total caloric intake.",
    isEssential: false,
  },
  {
    key: "monounsaturated_fat",
    name: "Monounsaturated Fat",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 25,
    description: "Heart-healthy fatty acids with one double bond (e.g., oleic acid found in olive oil).",
    isEssential: false,
  },
  {
    key: "polyunsaturated_fat",
    name: "Polyunsaturated Fat",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 15,
    description: "Fatty acids with multiple double bonds, including essential omega-3 and omega-6 lipids.",
    isEssential: true,
  },
  {
    key: "omega_3",
    name: "Omega-3",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 1.6,
    description: "Anti-inflammatory polyunsaturated fatty acids: ALA, EPA, and DHA.",
    isEssential: true,
  },
  {
    key: "omega_6",
    name: "Omega-6",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "RANGE",
    defaultDailyTarget: 14,
    defaultUpperLimit: 20,
    description: "Essential polyunsaturated fatty acid (Linoleic Acid) required for cellular membrane integrity.",
    isEssential: true,
  },
  {
    key: "trans_fat",
    name: "Trans Fat",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "MAXIMUM",
    defaultUpperLimit: 0,
    description: "Hydrogenated industrial fats; recommended to minimize as close to zero as possible.",
    isEssential: false,
  },
  {
    key: "sugar",
    name: "Sugar",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "MAXIMUM",
    defaultUpperLimit: 50,
    description: "Total simple mono- and disaccharides (naturally occurring + added).",
    isEssential: false,
  },
  {
    key: "added_sugar",
    name: "Added Sugar",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "MAXIMUM",
    defaultUpperLimit: 25,
    description: "Free sugars added during food processing, cooking, or preparation.",
    isEssential: false,
  },
  {
    key: "fibre",
    name: "Fibre",
    category: "MACRONUTRIENT",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 35,
    description: "Non-digestible complex carbohydrates vital for gut microbiome and glycemic control.",
    isEssential: true,
  },
  {
    key: "water",
    name: "Water",
    category: "MACRONUTRIENT",
    unit: "ml",
    targetType: "MINIMUM",
    defaultDailyTarget: 2800,
    description: "Total hydration volume consumed from fluids and moisture in whole foods.",
    isEssential: true,
  },

  // =========================================================================
  // 2. VITAMINS (13)
  // =========================================================================
  {
    key: "vitamin_a",
    name: "Vitamin A",
    category: "VITAMIN",
    unit: "µg RAE",
    targetType: "MINIMUM",
    defaultDailyTarget: 900,
    defaultUpperLimit: 3000,
    description: "Essential fat-soluble retinoid required for visual phototransduction and epithelial health.",
    isEssential: true,
  },
  {
    key: "vitamin_b1",
    name: "Vitamin B1",
    category: "VITAMIN",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 1.2,
    description: "Thiamine: cofactor for pyruvate dehydrogenase in glucose metabolism and energy conversion.",
    isEssential: true,
  },
  {
    key: "vitamin_b2",
    name: "Vitamin B2",
    category: "VITAMIN",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 1.3,
    description: "Riboflavin: central component of FMN/FAD cofactors driving the mitochondrial electron transport chain.",
    isEssential: true,
  },
  {
    key: "vitamin_b3",
    name: "Vitamin B3",
    category: "VITAMIN",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 16,
    defaultUpperLimit: 35,
    description: "Niacin: precursor to NAD+/NADH required for cellular repair, longevity, and oxidative phosphorylation.",
    isEssential: true,
  },
  {
    key: "vitamin_b5",
    name: "Vitamin B5",
    category: "VITAMIN",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 5.0,
    description: "Pantothenic Acid: indispensable for Coenzyme A (CoA) synthesis and lipid metabolism.",
    isEssential: true,
  },
  {
    key: "vitamin_b6",
    name: "Vitamin B6",
    category: "VITAMIN",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 1.7,
    defaultUpperLimit: 100,
    description: "Pyridoxine: cofactor for transamination of amino acids and neurotransmitter synthesis.",
    isEssential: true,
  },
  {
    key: "vitamin_b7",
    name: "Vitamin B7",
    category: "VITAMIN",
    unit: "µg",
    targetType: "MINIMUM",
    defaultDailyTarget: 30,
    description: "Biotin: prosthetic group for carboxylase enzymes in gluconeogenesis and fatty acid synthesis.",
    isEssential: true,
  },
  {
    key: "vitamin_b9",
    name: "Vitamin B9",
    category: "VITAMIN",
    unit: "µg DFE",
    targetType: "MINIMUM",
    defaultDailyTarget: 400,
    defaultUpperLimit: 1000,
    description: "Folate: essential for one-carbon metabolism, DNA methylation, and erythrocyte synthesis.",
    isEssential: true,
  },
  {
    key: "vitamin_b12",
    name: "Vitamin B12",
    category: "VITAMIN",
    unit: "µg",
    targetType: "MINIMUM",
    defaultDailyTarget: 2.4,
    description: "Cobalamin: cofactor for methionine synthase and myelin sheath maintenance.",
    isEssential: true,
  },
  {
    key: "vitamin_c",
    name: "Vitamin C",
    category: "VITAMIN",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 90,
    defaultUpperLimit: 2000,
    description: "Ascorbic Acid: potent antioxidant and reducing agent for prolyl/lysyl hydroxylase in collagen synthesis.",
    isEssential: true,
  },
  {
    key: "vitamin_d",
    name: "Vitamin D",
    category: "VITAMIN",
    unit: "µg",
    targetType: "MINIMUM",
    defaultDailyTarget: 20,
    defaultUpperLimit: 100,
    description: "Cholecalciferol: secosteroid hormone regulating calcium homeostasis, bone density, and immune function.",
    isEssential: true,
  },
  {
    key: "vitamin_e",
    name: "Vitamin E",
    category: "VITAMIN",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 15,
    defaultUpperLimit: 1000,
    description: "Alpha-tocopherol: primary lipid-soluble antioxidant protecting cell membranes from lipid peroxidation.",
    isEssential: true,
  },
  {
    key: "vitamin_k",
    name: "Vitamin K",
    category: "VITAMIN",
    unit: "µg",
    targetType: "MINIMUM",
    defaultDailyTarget: 120,
    description: "Phylloquinone & Menaquinones: essential for gamma-carboxylation of clotting factors and osteocalcin.",
    isEssential: true,
  },

  // =========================================================================
  // 3. MINERALS (13)
  // =========================================================================
  {
    key: "calcium",
    name: "Calcium",
    category: "MINERAL",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 1000,
    defaultUpperLimit: 2500,
    description: "Primary structural mineral for skeletal matrix, muscular contraction, and neuromuscular signaling.",
    isEssential: true,
  },
  {
    key: "iron",
    name: "Iron",
    category: "MINERAL",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 14,
    defaultUpperLimit: 45,
    description: "Core constituent of hemoglobin and myoglobin required for systemic oxygen transport.",
    isEssential: true,
  },
  {
    key: "magnesium",
    name: "Magnesium",
    category: "MINERAL",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 420,
    defaultUpperLimit: 350,
    description: "Cofactor in over 300 enzymatic reactions regulating ATP synthesis, protein synthesis, and muscle relaxation.",
    isEssential: true,
  },
  {
    key: "phosphorus",
    name: "Phosphorus",
    category: "MINERAL",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 700,
    defaultUpperLimit: 4000,
    description: "Essential component of nucleic acids, phospholipids, and high-energy ATP/ADP bonds.",
    isEssential: true,
  },
  {
    key: "potassium",
    name: "Potassium",
    category: "MINERAL",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 3400,
    description: "Primary intracellular cation regulating osmotic balance, action potentials, and vascular tone.",
    isEssential: true,
  },
  {
    key: "sodium",
    name: "Sodium",
    category: "MINERAL",
    unit: "mg",
    targetType: "RANGE",
    defaultDailyTarget: 2300,
    defaultUpperLimit: 2300,
    description: "Primary extracellular cation governing plasma volume, electrolyte balance, and nerve transmission.",
    isEssential: true,
  },
  {
    key: "zinc",
    name: "Zinc",
    category: "MINERAL",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 11,
    defaultUpperLimit: 40,
    description: "Catalytic component in >100 metalloenzymes controlling DNA transcription, immunity, and wound repair.",
    isEssential: true,
  },
  {
    key: "copper",
    name: "Copper",
    category: "MINERAL",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 0.9,
    defaultUpperLimit: 10,
    description: "Cofactor for cytochrome c oxidase and ceruloplasmin in mitochondrial respiration and iron oxidation.",
    isEssential: true,
  },
  {
    key: "manganese",
    name: "Manganese",
    category: "MINERAL",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 2.3,
    defaultUpperLimit: 11,
    description: "Essential trace element for mitochondrial superoxide dismutase (MnSOD) and cartilage formation.",
    isEssential: true,
  },
  {
    key: "selenium",
    name: "Selenium",
    category: "MINERAL",
    unit: "µg",
    targetType: "MINIMUM",
    defaultDailyTarget: 55,
    defaultUpperLimit: 400,
    description: "Constituent of selenoproteins including glutathione peroxidases and iodothyronine deiodinases.",
    isEssential: true,
  },
  {
    key: "chromium",
    name: "Chromium",
    category: "MINERAL",
    unit: "µg",
    targetType: "MINIMUM",
    defaultDailyTarget: 35,
    description: "Potentiates insulin signaling and carbohydrate/lipid metabolism via chromodulin binding.",
    isEssential: true,
  },
  {
    key: "molybdenum",
    name: "Molybdenum",
    category: "MINERAL",
    unit: "µg",
    targetType: "MINIMUM",
    defaultDailyTarget: 45,
    defaultUpperLimit: 2000,
    description: "Cofactor for sulfite oxidase and xanthine oxidase in sulfur amino acid catabolism and purine breakdown.",
    isEssential: true,
  },
  {
    key: "iodine",
    name: "Iodine",
    category: "MINERAL",
    unit: "µg",
    targetType: "MINIMUM",
    defaultDailyTarget: 150,
    defaultUpperLimit: 1100,
    description: "Integral structural component of thyroid hormones T3 and T4 regulating metabolic rate.",
    isEssential: true,
  },

  // =========================================================================
  // 4. AMINO ACIDS (15)
  // =========================================================================
  {
    key: "histidine",
    name: "Histidine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 1.0,
    description: "Essential amino acid precursor to histamine and carnosine; vital for myelin maintenance.",
    isEssential: true,
  },
  {
    key: "isoleucine",
    name: "Isoleucine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 1.4,
    description: "Branched-chain amino acid (BCAA) promoting muscular glucose uptake and hemoglobin synthesis.",
    isEssential: true,
  },
  {
    key: "leucine",
    name: "Leucine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 3.0,
    description: "Primary branched-chain amino acid trigger for mTORC1 and muscle protein synthesis (MPS).",
    isEssential: true,
  },
  {
    key: "lysine",
    name: "Lysine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 2.5,
    description: "Essential amino acid for carnitine synthesis, collagen crosslinking, and antiviral immune response.",
    isEssential: true,
  },
  {
    key: "methionine",
    name: "Methionine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 1.1,
    description: "Sulfur-containing essential amino acid precursor for S-adenosylmethionine (SAMe) and glutathione.",
    isEssential: true,
  },
  {
    key: "phenylalanine",
    name: "Phenylalanine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 2.2,
    description: "Essential aromatic amino acid precursor for tyrosine, dopamine, norepinephrine, and epinephrine.",
    isEssential: true,
  },
  {
    key: "threonine",
    name: "Threonine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 1.4,
    description: "Essential amino acid critical for mucin synthesis, gut barrier function, and tooth enamel.",
    isEssential: true,
  },
  {
    key: "tryptophan",
    name: "Tryptophan",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 0.35,
    description: "Essential amino acid precursor to serotonin, melatonin, and endogenous niacin synthesis.",
    isEssential: true,
  },
  {
    key: "valine",
    name: "Valine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 1.8,
    description: "Branched-chain amino acid (BCAA) required for muscle metabolism, repair, and nitrogen balance.",
    isEssential: true,
  },
  {
    key: "arginine",
    name: "Arginine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 4.0,
    description: "Conditionally essential amino acid substrate for endothelial nitric oxide synthase (eNOS) and vasodilation.",
    isEssential: false,
  },
  {
    key: "cysteine",
    name: "Cysteine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 0.8,
    description: "Sulfur amino acid rate-limiting for intracellular glutathione biosynthesis.",
    isEssential: false,
  },
  {
    key: "glutamine",
    name: "Glutamine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 5.0,
    description: "Most abundant free amino acid; primary fuel for enterocytes and immune lymphocytes.",
    isEssential: false,
  },
  {
    key: "glycine",
    name: "Glycine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 3.0,
    description: "Simplest amino acid making up 1/3 of collagen; essential for heme synthesis and bile salt conjugation.",
    isEssential: false,
  },
  {
    key: "proline",
    name: "Proline",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 2.5,
    description: "Cyclic amino acid critical for triple-helix stability of collagen and joint connective tissue.",
    isEssential: false,
  },
  {
    key: "tyrosine",
    name: "Tyrosine",
    category: "AMINO_ACID",
    unit: "g",
    targetType: "MINIMUM",
    defaultDailyTarget: 1.5,
    description: "Precursor for catecholamines (dopamine, adrenaline), thyroid hormones, and melanin pigments.",
    isEssential: false,
  },

  // =========================================================================
  // 5. OTHER NUTRIENTS & CAROTENOIDS (7)
  // =========================================================================
  {
    key: "choline",
    name: "Choline",
    category: "OTHER",
    unit: "mg",
    targetType: "MINIMUM",
    defaultDailyTarget: 550,
    defaultUpperLimit: 3500,
    description: "Essential quaternary ammonium compound for acetylcholine synthesis, membrane phosphatidylcholine, and lipid export.",
    isEssential: true,
  },
  {
    key: "cholesterol",
    name: "Cholesterol",
    category: "OTHER",
    unit: "mg",
    targetType: "MAXIMUM",
    defaultUpperLimit: 300,
    description: "Dietary sterol modulating membrane fluidity; precursor for bile acids and vitamin D.",
    isEssential: false,
  },
  {
    key: "beta_carotene",
    name: "Beta Carotene",
    category: "OTHER",
    unit: "µg",
    targetType: "REFERENCE",
    description: "Provitamin A carotenoid and potent lipid-soluble antioxidant.",
    isEssential: false,
  },
  {
    key: "lutein",
    name: "Lutein",
    category: "OTHER",
    unit: "µg",
    targetType: "REFERENCE",
    description: "Xanthophyll carotenoid concentrating in the retinal macula lutea to filter high-energy blue light.",
    isEssential: false,
  },
  {
    key: "zeaxanthin",
    name: "Zeaxanthin",
    category: "OTHER",
    unit: "µg",
    targetType: "REFERENCE",
    description: "Macular carotenoid working synergistically with lutein to protect retinal photoreceptors.",
    isEssential: false,
  },
  {
    key: "lycopene",
    name: "Lycopene",
    category: "OTHER",
    unit: "µg",
    targetType: "REFERENCE",
    description: "Acyclic carotenoid antioxidant offering vascular and prostate protective benefits.",
    isEssential: false,
  },
  {
    key: "ash",
    name: "Ash",
    category: "OTHER",
    unit: "g",
    targetType: "REFERENCE",
    description: "Total inorganic mineral residue remaining after complete combustion of organic matter in food.",
    isEssential: false,
  },
];

export class NutrientTaxonomyRegistry {
  private static nutrientMap = new Map<string, NutrientDefinition>(
    COMPLETE_NUTRIENT_TAXONOMY.map((n) => [n.key, n])
  );

  static getAll(): NutrientDefinition[] {
    return COMPLETE_NUTRIENT_TAXONOMY;
  }

  static getByKey(key: string): NutrientDefinition | undefined {
    return this.nutrientMap.get(key);
  }

  static getByCategory(category: NutrientCategory): NutrientDefinition[] {
    return COMPLETE_NUTRIENT_TAXONOMY.filter((n) => n.category === category);
  }

  static getKeys(): string[] {
    return COMPLETE_NUTRIENT_TAXONOMY.map((n) => n.key);
  }

  static getTotalCount(): number {
    return COMPLETE_NUTRIENT_TAXONOMY.length;
  }
}
